name: Nayan Prakash Mehta
favicon: null
layout_spectrum: 0.25613
typography_spectrum: 0.00686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5eef1'
    - '#00c6cd'
    - '#6b5a56'
    - '#cd9b80'
    - '#003339'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
