name: Nayan Prakash Mehta
favicon: null
layout_spectrum: 0.74484
typography_spectrum: 0.00686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#d1d1d1'
    - '#6f6f6f'
    - '#999999'
    - '#444444'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
